---
- name: Build a new VM via Tower and PowerVC/OpenStack with 1 network interfaces and Pool IP
# This playbook requires new VM name, image, flavor, network
  hosts: localhost
  gather_facts: false

# If calling from Tower the following variables need to be entered
  vars_prompt:
    - name: "VM_Name"
      prompt: "Enter name of new VM to create"
 #   - name: "VM_Net_Name_1"
 #     prompt: "Enter name of primary network"
 #   - name: "VM_Image_Name"
 #     prompt: "Enter name of image to use"
 #   - name: "VM_Flavor_Name"
 #     prompt: "Enter name of compute template to use"

  tasks:
  - name: Retrieve VM list
    openstack.cloud.server_info:
 #     filters:
 #       name: "{{ VM_Name }}"
    register: VM_Name_result

  - name: Show results
    debug:
      var: VM_Name_result
