---
- name: Check jobs 
  hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi
  tasks:
  - name: Check jobs
    ibm.power_ibmi.ibmi_cl_command:
      cmd: 'NETSTAT *CNN'
    register: running_jobs

  - name: Show jobs
    debug:
      var: running_jobs
    
  