---
- name: Create IBMi users 
  hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi
  tasks:
  - name: Create User
    ibm.power_ibmi.ibmi_user_and_group:
      operation: 'create'
      user: 'demouser'
    tags: create

  - name: Display User
    ibm.power_ibmi.ibmi_user_and_group:
      operation: 'display'
      user: 'demouser'
    tags: display
    register: userdata
    
  - debug: var=userdata
    tags: display
