---
- name: Remove IBMi users 
  hosts: all
  gather_facts: false
  collections:
    - ibm.power_ibmi
  tasks:
  - name: Remove User
    ibm.power_ibmi.ibmi_user_and_group:
      operation: 'delete'
      user: 'demouser'
    register: result_remove_user

  - name: Show result of remove user
    debug:
      var: result_remove_user.running_jobs.stdout
    
  