---
# Simple playbook to set facts about a VM from gathered facts and command execution
- name: Show VM details
  hosts: localhost
  gather_facts: yes

  collections:
    - ibm.cloudcollection
    
  tasks:
    - name: Collect existing Virtual Server Instance information
      ibm.cloudcollection.ibm_pi_instance_info:
         pi_instance_name: "{{ vsi_name }}"
         pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
         ibmcloud_api_key: "{{ api_key }}"
         region: "lon"
         zone: "lon04"
      register: pi_instance_existing_output

    - name: Show PI Instance
      debug:
        var: pi_instance_existing_output
    
